version: "3"

services:
  django:
    build:
      context: ./mat-backend
      dockerfile: Dockerfile
    container_name: django_container
    expose:
      - "8000"

  react:
    build:
      context: ./mat-frontend
      dockerfile: Dockerfile
    container_name: react_container
    expose:
      - "80"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_container
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
      - react
    volumes:
      - /etc/letsencrypt/live/mat.matcon.in/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/mat.matcon.in/privkey.pem:/etc/ssl/private/privkey.pem
      - /home/matcon/nginx/nginx.conf:/etc/nginx/nginx.conf
